when:
    - event: push
      branch: "**"

steps:
    - name: Build and Test (race)
      image: jcalabro/zu:2025-08-30
      commands: |
          zig build --summary all -freference-trace -Drace || true
          zig build --summary all -freference-trace -Drace
          ./zig-out/bin/zu

    - name: Build and Test (valgrind)
      image: jcalabro/zu:2025-08-30
      commands: |
          zig build --summary all -freference-trace -Doptimize=ReleaseSafe || true
          zig build --summary all -freference-trace -Doptimize=ReleaseSafe
          valgrind --leak-check=full --error-exitcode=1 ./zig-out/bin/zu

    - name: Build and Test (release)
      image: jcalabro/zu:2025-08-30
      commands: |
          zig build --summary all -freference-trace -Doptimize=ReleaseSafe || true
          zig build --summary all -freference-trace -Doptimize=ReleaseSafe
          ./zig-out/bin/zu
